package com.sgasubtitler;
import com.sgasubtitler.engine.*;import com.sgasubtitler.model.*;import java.nio.file.*;import java.security.*;import java.util.*;
public final class EngineTest {public static void main(String[]args)throws Exception{Path root=Path.of(".");var parser=new SgaParser();Map<String,Integer> counts=Map.of("Night Trap.SGA",2352,"Sewer Shark.SGA",2240,"Double Switch.SGA",1244,"Ground Zero Texas.SGA",1876);Map<String,SgaFile>files=new HashMap<>();for(var e:counts.entrySet()){var f=parser.parse(root.resolve(e.getKey()));files.put(e.getKey(),f);assert f.chunks().size()==e.getValue():e;assert !f.profile().isBlank();assert !f.supportSummary().isBlank();}var night=files.get("Night Trap.SGA");assert night.profile().equals("C1");var image=new C1Codec().decode(night.videoChunks().getFirst(),null);assert image.getWidth()==168&&image.getHeight()==104;var subs=new SrtParser().parse("1\n00:00:00,000 --> 00:00:00,200\nBonjour Mega-CD !\nDeuxième ligne\n\n2\n00:00:01,000 --> 00:00:02,000\nSuite\n");assert subs.size()==2&&subs.getFirst().text().contains("\n");byte[]before=Files.readAllBytes(root.resolve("Night Trap.SGA"));Path out=Files.createTempFile("night-trap-java-",".SGA");Files.delete(out);var encoder=new C1SubtitleEncoder();var report=encoder.encode(night,subs,SubtitleStyle.defaults(),out);byte[]afterSource=Files.readAllBytes(root.resolve("Night Trap.SGA")),patched=Files.readAllBytes(out);assert Arrays.equals(before,afterSource);assert patched.length==before.length;assert report.audioModified()==0;assert report.modifiedChunks()>0;assertAudioEqual(night,before,patched);Path wav=Files.createTempFile("night-trap-java-",".wav");new WavExporter().export(night,wav);assert Files.size(wav)>1_000_000;Files.deleteIfExists(out);Files.deleteIfExists(wav);
byte[]lzSource=new byte[8192];new Random(42).nextBytes(lzSource);for(int i=1024;i<4096;i++)lzSource[i]=lzSource[i%256];for(int[]params:new int[][]{{0xE000,0},{0xE000,1},{0xF000,1}}){byte[]packed=LzEncoder.encode(lzSource,params[0],params[1]);byte[]unpacked=LzDecoder.decode(packed,params[0],params[1]);assert Arrays.equals(lzSource,Arrays.copyOf(unpacked,lzSource.length));}
var sewer=files.get("Sewer Shark.SGA");assert sewer.profile().equals("C8");assert new VideoDecoder().decode(sewer,0).getWidth()==144;byte[]c8=encoder.encodeChunk(sewer.videoChunks().getFirst(),"TEST",SubtitleStyle.defaults());assert c8.length==sewer.videoChunks().getFirst().reportedLength();
var ds=files.get("Double Switch.SGA");assert ds.profile().equals("C9 + CD");byte[]c9=encoder.encodeChunk(ds.videoChunks().stream().filter(c->c.type()==0xC9).findFirst().orElseThrow(),"TEST",SubtitleStyle.defaults());assert c9.length>0;byte[]cd=encoder.encodeChunk(ds.videoChunks().stream().filter(c->c.type()==0xCD).findFirst().orElseThrow(),"TEST",SubtitleStyle.defaults());assert cd.length>0;
var gzt=files.get("Ground Zero Texas.SGA");var eDecoder=new VideoDecoder();for(int i=0;i<3;i++){var frame=eDecoder.decode(gzt,i);assert frame.getWidth()==192&&frame.getHeight()==128;}
for(var fixture:List.of(sewer,ds)){Path compressedOut=Files.createTempFile("compressed-profile-",".SGA");Files.delete(compressedOut);byte[]source=fixture.bytes().clone();var compressedReport=encoder.encode(fixture,List.of(new Subtitle(1,0,50,"TEST")),SubtitleStyle.defaults(),compressedOut);byte[]result=Files.readAllBytes(compressedOut);assert result.length==source.length;assert compressedReport.audioModified()==0;assert compressedReport.modifiedChunks()==1;assertAudioEqual(fixture,source,result);assert Arrays.equals(source,fixture.bytes());Files.delete(compressedOut);}
workflow(parser,night,false);workflow(parser,sewer,false);workflow(parser,ds,false);workflow(parser,gzt,true);
System.out.println("Java engine tests passed: 4 fixtures, C1/C8/C9/CD/E8/E9 decode, LZ encode round-trips, C1/C8/C9/CD fixed allocations, SRT, audio and WAV");}
private static void workflow(SgaParser parser,SgaFile source,boolean e8)throws Exception{byte[]original=source.bytes().clone();Path output=Files.createTempFile("sga-v06-workflow-",".SGA");Files.delete(output);var style=e8?new SubtitleStyle("SansSerif",8,true,SubtitleStyle.Position.BAS,0,1):SubtitleStyle.defaults();var captions=List.of(new Subtitle(1,0,50,e8?"I":"TEST"));var report=e8?new E8SubtitleEncoder().encode(source,captions,style,output):new C1SubtitleEncoder().encode(source,captions,style,output);assert report.originalSize()==report.outputSize();assert report.audioModified()==0;assert report.offsetsPreserved();SgaFile reopened=parser.parse(output);assert reopened.bytes().length==source.bytes().length;assert reopened.profile().equals(source.profile());assertAudioEqual(source,source.bytes(),reopened.bytes());assert Arrays.equals(original,source.bytes());var before=new VideoDecoder().decode(source,0);var after=new VideoDecoder().decode(reopened,0);assert pixelsDiffer(before,after);Files.delete(output);}
private static boolean pixelsDiffer(java.awt.image.BufferedImage a,java.awt.image.BufferedImage b){for(int y=0;y<a.getHeight();y++)for(int x=0;x<a.getWidth();x++)if(a.getRGB(x,y)!=b.getRGB(x,y))return true;return false;}
private static void assertAudioEqual(SgaFile file,byte[]a,byte[]b){for(var c:file.audioChunks())for(var s:c.spans())for(int i=0;i<s.length();i++)assert a[(int)s.offset()+i]==b[(int)s.offset()+i];}}
