package com.sgasubtitler.ui;
import com.sgasubtitler.engine.*;import com.sgasubtitler.model.*;import javax.swing.*;import javax.swing.border.*;import javax.swing.table.*;import java.awt.*;import java.awt.event.*;import java.io.*;import java.nio.file.*;import java.util.*;import java.util.List;import java.util.concurrent.Callable;import java.util.function.Consumer;
public final class MainFrame extends JFrame {
 private static final Color BG=new Color(7,18,32),CARD=new Color(14,31,49),LINE=new Color(43,68,94),TEXT=new Color(234,241,251),MUTED=new Color(151,174,202),BLUE=new Color(20,130,246);
 private SgaFile sga;private List<Subtitle>subs=List.of();private Path srtPath;private SubtitleStyle style=SubtitleStyle.defaults();private final PreviewPanel preview=new PreviewPanel();private final JLabel info=new JLabel("Aucun fichier SGA chargé"),srtInfo=new JLabel("Aucun fichier SRT chargé"),time=new JLabel("00:00.000 / 00:00.000");private final JSlider timeline=new JSlider(),size=new JSlider(8,28,14),vertical=new JSlider(-30,30,0);private final JComboBox<String>font=new JComboBox<>(new String[]{Font.SANS_SERIF,Font.SERIF,Font.MONOSPACED,Font.DIALOG,Font.DIALOG_INPUT});private final JComboBox<SubtitleStyle.Position>position=new JComboBox<>(SubtitleStyle.Position.values());private final JCheckBox bold=new JCheckBox("Gras",true);private final DefaultTableModel tableModel=new DefaultTableModel(new String[]{"#","Début","Fin","Texte"},0){public boolean isCellEditable(int r,int c){return false;}};private final javax.swing.Timer timer;
 public MainFrame(){super("SGA Subtitler V0.6");setDefaultCloseOperation(EXIT_ON_CLOSE);setMinimumSize(new Dimension(1180,760));setSize(1440,900);setLocationRelativeTo(null);setContentPane(build());timer=new javax.swing.Timer(67,e->{if(sga!=null&&timeline.getValue()<timeline.getMaximum())timeline.setValue(timeline.getValue()+1);else((javax.swing.Timer)e.getSource()).stop();});timeline.addChangeListener(e->refreshPreview());size.addChangeListener(e->updateStyle());vertical.addChangeListener(e->updateStyle());font.addActionListener(e->updateStyle());position.addActionListener(e->updateStyle());bold.addActionListener(e->updateStyle());}
 private JPanel build(){JPanel root=new JPanel(new BorderLayout(12,12));root.setBackground(BG);root.setBorder(new EmptyBorder(0,14,14,14));root.add(header(),BorderLayout.NORTH);JPanel center=new JPanel(new BorderLayout(12,12));center.setOpaque(false);center.add(left(),BorderLayout.WEST);center.add(player(),BorderLayout.CENTER);center.add(right(),BorderLayout.EAST);center.add(subtitleTable(),BorderLayout.SOUTH);root.add(center);return root;}
 private JComponent header(){JPanel h=new JPanel(new BorderLayout());h.setPreferredSize(new Dimension(100,145));h.setBackground(new Color(3,14,29));try{var img=new ImageIcon(Objects.requireNonNull(getClass().getResource("/interface-reference.png"))).getImage();h=new JPanel(new BorderLayout()){protected void paintComponent(Graphics g){super.paintComponent(g);g.drawImage(img,0,0,getWidth(),145,0,0,1536,170,this);}};h.setOpaque(true);}catch(Exception ignored){}JLabel badge=new JLabel("SGA Subtitler   V0.6",SwingConstants.RIGHT);badge.setForeground(TEXT);badge.setFont(new Font(Font.SANS_SERIF,Font.BOLD,17));badge.setBorder(new EmptyBorder(0,0,8,20));h.add(badge,BorderLayout.SOUTH);return h;}
 private JComponent left(){JPanel p=card("Fichier SGA");p.setPreferredSize(new Dimension(285,100));p.add(button("OUVRIR SGA",e->openSga()));info.setForeground(MUTED);info.setVerticalAlignment(SwingConstants.TOP);p.add(info);p.add(button("EXTRAIRE WAV",e->extractWav()));return p;}
 private JComponent player(){JPanel p=card("Prévisualisation vidéo");p.add(preview);timeline.setMaximum(0);timeline.setOpaque(false);p.add(timeline);JPanel controls=new JPanel(new FlowLayout());controls.setOpaque(false);JButton play=button("▶  LECTURE / PAUSE",e->{if(timer.isRunning())timer.stop();else timer.start();});controls.add(play);time.setForeground(MUTED);controls.add(time);p.add(controls);return p;}
 private JComponent right(){JPanel wrap=new JPanel();wrap.setOpaque(false);wrap.setPreferredSize(new Dimension(315,100));wrap.setLayout(new BoxLayout(wrap,BoxLayout.Y_AXIS));JPanel s=card("Fichier SRT");s.setMaximumSize(new Dimension(Integer.MAX_VALUE,130));s.add(button("CHARGER SRT",e->openSrt()));srtInfo.setForeground(MUTED);s.add(srtInfo);wrap.add(s);wrap.add(Box.createVerticalStrut(10));JPanel st=card("Style des sous-titres");st.add(row("Police",font));st.add(row("Taille",size));st.add(row("Position",position));st.add(row("Ajustement vertical",vertical));bold.setOpaque(false);bold.setForeground(TEXT);st.add(bold);st.add(button("CRÉER LE SGA SOUS-TITRÉ",e->encode()));wrap.add(st);return wrap;}
 private JComponent subtitleTable(){JPanel p=card("Liste des sous-titres");p.setPreferredSize(new Dimension(100,220));JTable t=new JTable(tableModel);t.setBackground(new Color(11,27,43));t.setForeground(TEXT);t.setGridColor(LINE);t.setRowHeight(25);t.getTableHeader().setBackground(new Color(20,42,65));t.getTableHeader().setForeground(TEXT);p.add(new JScrollPane(t));return p;}
 private JPanel card(String title){JPanel panel=new JPanel();panel.setLayout(new BoxLayout(panel,BoxLayout.Y_AXIS));panel.setBackground(CARD);panel.setBorder(new CompoundBorder(new LineBorder(LINE,1,true),new EmptyBorder(12,12,12,12)));JLabel l=new JLabel(title);l.setForeground(TEXT);l.setFont(l.getFont().deriveFont(Font.BOLD,16));l.setAlignmentX(Component.LEFT_ALIGNMENT);panel.add(l);panel.add(Box.createVerticalStrut(8));return panel;}
 private JPanel row(String name,JComponent c){JPanel r=new JPanel(new BorderLayout(8,4));r.setOpaque(false);JLabel l=new JLabel(name);l.setForeground(MUTED);r.add(l,BorderLayout.WEST);r.add(c);return r;}
 private JButton button(String text,ActionListener listener){JButton b=new JButton(text);b.setBackground(BLUE);b.setForeground(Color.WHITE);b.setFont(b.getFont().deriveFont(Font.BOLD,13));b.setFocusPainted(false);b.setBorder(new EmptyBorder(11,15,11,15));b.setAlignmentX(Component.LEFT_ALIGNMENT);b.addActionListener(listener);return b;}
 private void openSga(){Path p=choose(false,"SGA",null);if(p==null)return;runAsync("Analyse du SGA…",()->new SgaParser().parse(p),loaded->{sga=loaded;var v=sga.videoChunks().getFirst();timeline.setMaximum(Math.max(0,sga.videoChunks().size()-1));timeline.setValue(0);var a=sga.audioChunks().isEmpty()?null:SgaFile.AudioInfo.of(sga.audioChunks().getFirst());info.setText("<html><b>"+p.getFileName()+"</b><br>"+sga.bytes().length+" octets<br>Famille: "+sga.knownFamily()+"<br>Profil: "+sga.profile()+"<br>Résolution: "+v.width()+" × "+v.height()+"<br>Durée: "+format((long)(sga.durationSeconds()*1000))+"<br>Chunks: "+sga.chunkSummary()+"<br>Audio: "+(a==null?"Non":a.rate()+" Hz mono")+"<br>Support: "+sga.supportSummary()+"</html>");refreshPreview();});}
 private void openSrt(){Path p=choose(false,"SRT",null);if(p==null)return;runAsync("Lecture du SRT…",()->new SrtParser().parse(p),loaded->{subs=loaded;srtPath=p;tableModel.setRowCount(0);for(var subtitle:subs)tableModel.addRow(new Object[]{subtitle.number(),format(subtitle.startMillis()),format(subtitle.endMillis()),subtitle.text().replace('\n',' ')});srtInfo.setText("<html><b>"+p.getFileName()+"</b><br>✓ "+subs.size()+" sous-titres détectés</html>");refreshPreview();});}
 private void extractWav(){if(sga==null){error("Ouvrez d'abord un SGA");return;}Path p=choose(true,"WAV",sga.path().resolveSibling(base(sga.path())+".wav"));if(p!=null)runAsync("Extraction WAV…",()->{new WavExporter().export(sga,p);return p;},created->message("WAV créé sans modifier le SGA source:\n"+created));}
 private void encode(){if(sga==null||subs.isEmpty()){error("Un SGA et un SRT valides sont requis");return;}Path suggested=sga.path().resolveSibling(base(sga.path())+"_FR.SGA"),p=choose(true,"SGA",suggested);if(p==null)return;if(Files.exists(p)){error("Le fichier existe déjà. Choisissez un nouveau nom.");return;}runAsync("Création du SGA fixed-size…",()->sga.videoChunks().stream().allMatch(c->c.type()==0xE8||c.type()==0xE9)?new E8SubtitleEncoder().encode(sga,subs,style,p):new C1SubtitleEncoder().encode(sga,subs,style,p),r->message("SGA créé avec succès\nTaille identique: OUI\nChunks modifiés: "+r.modifiedChunks()+"\nAudio modifié: "+r.audioModified()+"\nOctets différents: "+r.differentBytes()+"\n"+p));}
 private void updateStyle(){style=new SubtitleStyle((String)font.getSelectedItem(),size.getValue(),bold.isSelected(),(SubtitleStyle.Position)position.getSelectedItem(),vertical.getValue(),2);refreshPreview();}
 private void refreshPreview(){if(sga==null)return;preview.setData(sga,subs,style,timeline.getValue());long now=Math.round(timeline.getValue()*1000d/sga.frameRate());time.setText(format(now)+" / "+format((long)(sga.durationSeconds()*1000)));}
 private Path choose(boolean save,String ext,Path suggested){JFileChooser c=new JFileChooser();if(suggested!=null)c.setSelectedFile(suggested.toFile());int r=save?c.showSaveDialog(this):c.showOpenDialog(this);return r==JFileChooser.APPROVE_OPTION?c.getSelectedFile().toPath():null;}
 private <T>void runAsync(String title,Callable<T>work,Consumer<T>success){JDialog progress=new JDialog(this,title,false);JProgressBar bar=new JProgressBar();bar.setIndeterminate(true);bar.setStringPainted(true);bar.setString(title);progress.add(bar);progress.setSize(360,75);progress.setLocationRelativeTo(this);progress.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));progress.setVisible(true);new SwingWorker<T,Void>(){protected T doInBackground()throws Exception{return work.call();}protected void done(){progress.dispose();setCursor(Cursor.getDefaultCursor());try{success.accept(get());}catch(Exception ex){Throwable cause=ex.getCause()==null?ex:ex.getCause();error(title+" impossible:\n"+cause.getMessage());}}}.execute();}
 private void error(String s){JOptionPane.showMessageDialog(this,s,"SGA Subtitler",JOptionPane.ERROR_MESSAGE);}private void message(String s){JOptionPane.showMessageDialog(this,s,"SGA Subtitler",JOptionPane.INFORMATION_MESSAGE);}private static String base(Path p){String n=p.getFileName().toString();int dot=n.lastIndexOf('.');return dot<0?n:n.substring(0,dot);}private static String format(long ms){return "%02d:%02d.%03d".formatted(ms/60000,(ms/1000)%60,ms%1000);}
}
